### ISSUE TITLE
Backup Log

### ISSUE THREAD

**Issue by zhandao** [zhandao/i_am_i_can#2]
- [ ] cache
- [ ] list instances that have given roles or permissions
- [ ] check the test which for testing multi-calling with same args **[next]**
- [ ] make_sure (controller helper) **[NEXT]**
- [ ] 解决在同一 querying 中查询多次相同的 stored_ **[next]**
- [ ] querying in ONE SQL
- [ ] test complete: group (include group#can), can_each, is_one_of .. **[next]**
- [ ] expire
- [ ] can manage User but cannot manage user
- [ ] group which_can
- [ ] he can manage User and user, if cannot manage User, should do also cannot manage user automaticlly?
- [ ] when auto define mode `Role Definition Done, but name ["string1"] have been used by other role or group` (redefine) **[next]**
- [ ] config: 可选择必须存储数据库，方法名取消前缀 stored
- [x] pred -> action **[next]**
- [ ] role status machine
- [ ] docs: errors, support diff subjects
- [ ] docs: why? features, performance, High customization
- [ ] User.which
- [ ] role.add user, 批量定义和赋予 **[NEXT]**
- [ ] remove_roles from group
- [ ] before and after action
- [ ]
- [ ]

**Comment by zhandao** [comment]
```ruby
# TODO: base_role => parent_role
# TODO: support multi-level tree
def org_roles *children, by_parent:, **options
  has_role  by_parent, options.merge!(children: children)
  has_roles children, options.merge!(parent: by_parent)
end
```

**Comment by zhandao** [comment]
```ruby
module PermissionQuerying
  def can? pred, obj0 = nil, obj: nil, without_group: false
    obj = obj0 || obj
    return true if temporarily_can?(pred, obj)
    # permission = ii_config.permission_model.which(pred: pred, obj: obj)
    # return true if is_one_of? *permission.related_roles.map(&:name)
    # stored_roles.each { |role| return true if role.can? pred, obj }
    return true if ii_config.permission_model.matched?(pred: pred, obj: obj, in: permissions_of_stored_roles)
    return false if without_group || ii_config.without_group
    # is_in_one_of? *permission.related_role_groups.map(&:name)
    ii_config.permission_model.matched?(pred: pred, obj: obj, in: permissions_of_role_groups)
  end
end
```

**Comment by zhandao** [comment]
- [x] doc
- [x] generator
- [x] which_can
- [x] role group disable
- [x] subject_am, subject_can
- [x] test for can? and can!
- [x] **cancel assigment**
- [x] has_array_of => has many thought **[NEXT]** and will be not limited db
- [x] configable filed name role_ids, permission_ids **[next]**
- [x] merge migrations to 1 file **[next]**
- [x] rails g option: role and permission model name **[next]**
- [x] def and assgin return true or false
- [x] 解决 User 类还没初始化时 method not found 问题
- [x] role group locally
- [x] test local permission **[next]**
- [x] maintainablity **[next]**
- [x] 测试自动清理 User 的 local role & permission
- [x] falls_from & cannot auto find both in local and db
- [x] dont show xx done if all fail **[next]** !!!
- [x] uniq index with deleted_at **[next]**
- [x] 不循环判断 all_of? **[NNNNEXT]**
- [x] use role and permission model name in methods, like `stored_my_roles` **[NEXT]**
- [x] `user.roles.permissions.where(pred: 'pull').objs(Source)`
      to: polymorphic `user.permissions(:pull, Source).objs` and `Source.that_allow(user).to(:pull)` **[next]**
- [x] can / falls ... could receive a record **[NEXT]** !!!
- [x] result return record or false
- [x] result dont print anything if do nothing
- [x] test pass record
- [x] 使用专门的入参层重构
- [x] saved in local，and then save to db，？=> 方案：定义互通，单向赋值（db -> temporary），且赋值时记录是 db 还是 local 的 role；查询权限时同时查：stored role 的 local 和 stored 权限
